export const GET_BANK_SUCCESS = 'GET_BANK_SUCCESS'
export const GET_BANK_FAILURE = 'GET_BANK_FAILURE'
export const GET_LAST_SUCCESS = 'GET_LAST_SUCCESS'
export const GET_LAST_FAILURE = 'GET_LAST_FAILURE'
